"""registration allow-list

Revision ID: bbd7a5bb606b
Revises: 95cbe30dc4b3
Create Date: 2026-09-16 15:23:32.624471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbd7a5bb606b'
down_revision: Union[str, Sequence[str], None] = '95cbe30dc4b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approved_emails',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('added_by_id', sa.String(length=36), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['added_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('approved_emails', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_approved_emails_email'), ['email'], unique=True)

    with op.batch_alter_table('agent_runs', schema=None) as batch_op:
        batch_op.alter_column('enable_diarization',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('attempts',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_runs', schema=None) as batch_op:
        batch_op.alter_column('attempts',
               existing_type=sa.INTEGER(),
               server_default=sa.text("'0'"),
               existing_nullable=False)
        batch_op.alter_column('enable_diarization',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('0'),
               existing_nullable=False)

    with op.batch_alter_table('approved_emails', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approved_emails_email'))

    op.drop_table('approved_emails')
    # ### end Alembic commands ###
